---
# Machine image tags listed at https://circleci.com/developer/machine/image/android
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.0

jobs:
  check-if-forked:
    docker: 
      - image: cimg/base:stable
    resource-class: small
    steps:
      - run:
          name: Evaluate whether running within repo or as forked PR
          command: |
            echo "CIRCLE_PR_USERNAME / CIRCLE_PR_REPONAME - $CIRCLE_PR_USERNAME / $CIRCLE_PR_REPONAME"
            if [ -z "$CIRCLE_PR_REPONAME "] #If this exists then it's a forked PR
            then
              echo '{}' | jq '. += { "oss-contribution-flow" : true}' >  pipeline-params.json            
            else
              echo '{}' | jq '.' > pipeline-params.json
            fi  
            
      - continuation/continue:
          parameters: pipeline-params.json
          configuration-path: .circleci/continue-pipeline-config.yml

workflows:
  always-run:
    jobs:
      - check-if-forked